spring.application.name=order-engine
#Server Configuration info
server.port=8081

#DBConnection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/elmsproject
spring.datasource.username=root
spring.datasource.password=root

#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true